baseURL = "https://memkit.xyz"
title = "memkit"
author = "username"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "memkit Logo"
    text = "memkit"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "memkit"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Distributed Solutions for a Better World"
    meta_og_title = "memkit"
    meta_og_type = "website"
    meta_og_url = "https://memkit.xyz"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Distributed Solutions for a Better World"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@memkit"
    meta_twitter_creator = "@mconstant_eth"

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/memkit"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
